
# title and description of the site (will be used in <title> tag)
title: You are busier than you think
description: Adventures in Sara and Peter's small campervan
# use hacker theme
theme: jekyll-theme-hacker
# this is the base URL (use http://localhost:4000/blog/ to access locally)
baseurl: /blog
plugins:
  # use paginator plugin
  - jekyll-paginate
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
source: .
destination: ./_site
permalink: /:title
# display 3 posts in a page
paginate: 3
paginate_path: /page/:num/
# this will be displayed as the banner of the blog's home page
banner: "Really... you are busier than you thought..."
# your Github profile
github: https://github.com/Petermullarkey

