title: You're busier than you'd think
description: "Campervan adventures with Sara and Peter"
author:
  name: "Sara and Peter Mullarkey"
  email: "peter.mullarkey+cv@gmail.com"
  url: "https://petermullarkey.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Sara and Peter Mullarkey"
year : "2024"
